ci: revert merging build_to_wasm_and_upload

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -236,6 +236,86 @@ jobs:
             micromamba activate scipy-dev
             python dev.py test -t scipy.integrate -v
 
+  build_to_wasm_and_upload:
+    name: Build LFortran to WASM and Upload
+    runs-on: "ubuntu-latest"
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - uses: mamba-org/setup-micromamba@v1.8.0
+        with:
+          micromamba-version: '1.5.10-0'
+          environment-file: ci/environment_linux.yml
+          create-args: >-
+            python=3.10
+
+      - uses: hendrikmuhs/ccache-action@main
+        with:
+          variant: sccache
+          key: ${{ github.job }}-${{ matrix.os }}
+
+      - name : Remove existing node
+        shell: bash -e -l {0}
+        run : |
+            which node
+            node -v
+            sudo rm -rf /usr/local/bin/node /usr/local/bin/npm
+
+      - name: Install Emscripten from Git
+        # TODO: This fails with "-e" for some reason:
+        shell: bash -l {0}
+        run: |
+            mkdir $HOME/ext
+            cd $HOME/ext
+
+            git clone https://github.com/emscripten-core/emsdk.git
+            cd emsdk
+
+            ./emsdk install 3.1.35
+
+            ./emsdk activate 3.1.35
+
+            ./emsdk install node-18.20.3-64bit
+
+            ./emsdk activate node-18.20.3-64bit
+
+      - name: Show Emscripten and Node Info
+        shell: bash -l {0}
+        run: |
+            set -ex
+            # Activate PATH and other environment variables in the current terminal
+            source $HOME/ext/emsdk/emsdk_env.sh
+            emcc -v
+            em++ -v
+            which node
+            node -v
+
+      - name: Build to WASM
+        shell: bash -l {0}
+        run: |
+            set -ex
+            source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
+            ./build_to_wasm.sh
+
+      - name: Test built lfortran.wasm
+        shell: bash -l {0}
+        run: |
+            set -ex
+            source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
+            which node
+            node -v
+            node src/lfortran/tests/test_lfortran.js
+
+      - name: Upload to wasm_builds
+        shell: bash -l {0}
+        run: |
+            ci/upload_lfortran_wasm.sh
+        env:
+          SSH_PRIVATE_KEY_WASM_BUILDS: ${{ secrets.SSH_PRIVATE_KEY_WASM_BUILDS }}
+
+
   debug_outOfSource:
     name: Check Out-of-Source Debug build
     runs-on: ubuntu-latest
@@ -1185,8 +1265,8 @@ jobs:
             ./run_tests.py -b llvm_wasm llvm_wasm_emcc --experimental-simplifier
 
 
-  lfortran_debug_build_backends_tarball_cpp_build_wasm_gfortran_build_to_wasm_and_upload:
-    name: Test GFortran, WASM Build and Upload, Debug Build, Fortran, OpenMP, C/C++ backend, Upload Tarball, CPP Build, WASM
+  lfortran_debug_build_backends_tarball_cpp_build_wasm_gfortran:
+    name: Test GFortran, Debug Build, Fortran, OpenMP, C/C++ backend, Upload Tarball, CPP Build, WASM
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -1227,66 +1307,6 @@ jobs:
           ci/upload_tarball_to_release.sh
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-
-      - name : Remove existing node
-        shell: bash -e -l {0}
-        run : |
-            which node
-            node -v
-            sudo rm -rf /usr/local/bin/node /usr/local/bin/npm
-
-      - name: Install Emscripten from Git
-        # TODO: This fails with "-e" for some reason:
-        shell: bash -l {0}
-        run: |
-            mkdir $HOME/ext
-            cd $HOME/ext
-
-            git clone https://github.com/emscripten-core/emsdk.git
-            cd emsdk
-
-            ./emsdk install 3.1.35
-
-            ./emsdk activate 3.1.35
-
-            ./emsdk install node-18.20.3-64bit
-
-            ./emsdk activate node-18.20.3-64bit
-
-      - name: Show Emscripten and Node Info
-        shell: bash -l {0}
-        run: |
-            set -ex
-            # Activate PATH and other environment variables in the current terminal
-            source $HOME/ext/emsdk/emsdk_env.sh
-            emcc -v
-            em++ -v
-            which node
-            node -v
-
-      - name: Build to WASM
-        shell: bash -l {0}
-        run: |
-            set -ex
-            source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
-            ./build_to_wasm.sh
-
-      - name: Test built lfortran.wasm
-        shell: bash -l {0}
-        run: |
-            set -ex
-            source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
-            which node
-            node -v
-            node src/lfortran/tests/test_lfortran.js
-
-      - name: Upload to wasm_builds
-        shell: bash -l {0}
-        run: |
-            ci/upload_lfortran_wasm.sh
-        env:
-          SSH_PRIVATE_KEY_WASM_BUILDS: ${{ secrets.SSH_PRIVATE_KEY_WASM_BUILDS }}
 
       - name: Test integration_tests with GFortran
         shell: bash -e -l {0}
