CI: comment out "Build LFortran to WASM and Upload" CI job

diff --git a/.github/workflows/QUICK.yml b/.github/workflows/QUICK.yml
--- a/.github/workflows/QUICK.yml
+++ b/.github/workflows/QUICK.yml
@@ -313,114 +313,114 @@ jobs:
       # end of SciPy related testing
 
       # the below code is taken from "Build LFortran to WASM and Upload" CI job
-      - name : Build LFortran to WASM and Upload - Remove existing node
-        shell: bash -e -l {0}
-        if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-        run : |
-            which node
-            node -v
-            sudo rm -rf /usr/local/bin/node /usr/local/bin/npm
-
-      - name: Build LFortran to WASM and Upload - Install Emscripten from Git
-        # TODO: This fails with "-e" for some reason:
-        shell: bash -l {0}
-        if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-        run: |
-            mkdir $HOME/ext
-            cd $HOME/ext
-
-            git clone https://github.com/emscripten-core/emsdk.git
-            cd emsdk
-
-            ./emsdk install 3.1.35
-
-            ./emsdk activate 3.1.35
-
-            ./emsdk install node-18.20.3-64bit
-
-            ./emsdk activate node-18.20.3-64bit
-
-      - name: Build LFortran to WASM and Upload - Show Emscripten and Node Info
-        shell: bash -l {0}
-        if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-        run: |
-            set -ex
-            # Activate PATH and other environment variables in the current terminal
-            source $HOME/ext/emsdk/emsdk_env.sh
-            emcc -v
-            em++ -v
-            which node
-            node -v
-
-      - name: Build LFortran to WASM and Upload - Build to WASM
-        shell: bash -l {0}
-        if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-        run: |
-            set -ex
-            source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
-            ./build_to_wasm.sh
-
-      - name: Build LFortran to WASM and Upload - Test built lfortran.wasm
-        shell: bash -l {0}
-        if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-        run: |
-            set -ex
-            source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
-            which node
-            node -v
-            node src/lfortran/tests/test_lfortran.js
-
-      - name: Build LFortran to WASM and Upload - Upload to wasm_builds
-        shell: bash -l {0}
-        if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-        run: |
-            ci/upload_lfortran_wasm.sh
-        env:
-          SSH_PRIVATE_KEY_WASM_BUILDS: ${{ secrets.SSH_PRIVATE_KEY_WASM_BUILDS }}
-      # end of "Build LFortran to WASM and Upload" CI job
-
-      # TODO: Maybe we want to run this on ubuntu with both the LLVM versions?
-      # the below code is taken from "Check Out-of-Source Debug build" job
-    #   - name: Build in debug mode on linux
-    #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-    #     shell: bash -e -x -l {0}
-    #     run: |
-    #         ( cd src && ./build0.sh )
-    #         export CXXFLAGS="-Werror"
-    #         cmake -S src -B builddir -GNinja \
-    #           -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-    #           -DWITH_LLVM=yes \
-    #           -DWITH_LSP=yes \
-    #           -DWITH_KOKKOS=yes \
-    #           -DLFORTRAN_BUILD_ALL=yes \
-    #           -DWITH_STACKTRACE=no \
-    #           -DWITH_RUNTIME_STACKTRACE=yes \
-    #           -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" \
-    #           -DCMAKE_INSTALL_PREFIX=`pwd`/inst \
-    #           -DCMAKE_C_COMPILER_LAUNCHER=sccache \
-    #           -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
-
-    #         cmake --build builddir  -j16 --target install
-
-    #   - name: Test debug build on linux
+    #   - name : Build LFortran to WASM and Upload - Remove existing node
     #     shell: bash -e -l {0}
     #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-    #     run: ctest --output-on-failure
-    #     working-directory: builddir
+    #     run : |
+    #         which node
+    #         node -v
+    #         sudo rm -rf /usr/local/bin/node /usr/local/bin/npm
 
-    #   - name: Test Moved Installation
+    #   - name: Build LFortran to WASM and Upload - Install Emscripten from Git
+    #     # TODO: This fails with "-e" for some reason:
+    #     shell: bash -l {0}
     #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
-    #     shell: bash -e -l {0}
     #     run: |
-    #       mv inst inst.moved
-    #       cp src/examples/expr2.f90 expr2.F90
-    #       rm -rf src
-    #       inst.moved/bin/lfortran expr2.F90 -o expr2
-    #       ./expr2
-    #       inst.moved/bin/lfortran --backend=c expr2.F90 -o expr2b
-    #       ./expr2b
-    #       inst.moved/bin/lfortran --openmp --backend=cpp expr2.F90 -o expr2c
-    #       ./expr2c
+    #         mkdir $HOME/ext
+    #         cd $HOME/ext
+
+    #         git clone https://github.com/emscripten-core/emsdk.git
+    #         cd emsdk
+
+    #         ./emsdk install 3.1.35
+
+    #         ./emsdk activate 3.1.35
+
+    #         ./emsdk install node-18.20.3-64bit
+
+    #         ./emsdk activate node-18.20.3-64bit
+
+    #   - name: Build LFortran to WASM and Upload - Show Emscripten and Node Info
+    #     shell: bash -l {0}
+    #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    #     run: |
+    #         set -ex
+    #         # Activate PATH and other environment variables in the current terminal
+    #         source $HOME/ext/emsdk/emsdk_env.sh
+    #         emcc -v
+    #         em++ -v
+    #         which node
+    #         node -v
+
+    #   - name: Build LFortran to WASM and Upload - Build to WASM
+    #     shell: bash -l {0}
+    #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    #     run: |
+    #         set -ex
+    #         source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
+    #         ./build_to_wasm.sh
+
+    #   - name: Build LFortran to WASM and Upload - Test built lfortran.wasm
+    #     shell: bash -l {0}
+    #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    #     run: |
+    #         set -ex
+    #         source $HOME/ext/emsdk/emsdk_env.sh # Activate Emscripten
+    #         which node
+    #         node -v
+    #         node src/lfortran/tests/test_lfortran.js
+
+    #   - name: Build LFortran to WASM and Upload - Upload to wasm_builds
+    #     shell: bash -l {0}
+    #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    #     run: |
+    #         ci/upload_lfortran_wasm.sh
+    #     env:
+    #       SSH_PRIVATE_KEY_WASM_BUILDS: ${{ secrets.SSH_PRIVATE_KEY_WASM_BUILDS }}
+    #   # end of "Build LFortran to WASM and Upload" CI job
+
+    #   # TODO: Maybe we want to run this on ubuntu with both the LLVM versions?
+    #   # the below code is taken from "Check Out-of-Source Debug build" job
+    # #   - name: Build in debug mode on linux
+    # #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    # #     shell: bash -e -x -l {0}
+    # #     run: |
+    # #         ( cd src && ./build0.sh )
+    # #         export CXXFLAGS="-Werror"
+    # #         cmake -S src -B builddir -GNinja \
+    # #           -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+    # #           -DWITH_LLVM=yes \
+    # #           -DWITH_LSP=yes \
+    # #           -DWITH_KOKKOS=yes \
+    # #           -DLFORTRAN_BUILD_ALL=yes \
+    # #           -DWITH_STACKTRACE=no \
+    # #           -DWITH_RUNTIME_STACKTRACE=yes \
+    # #           -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" \
+    # #           -DCMAKE_INSTALL_PREFIX=`pwd`/inst \
+    # #           -DCMAKE_C_COMPILER_LAUNCHER=sccache \
+    # #           -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
+
+    # #         cmake --build builddir  -j16 --target install
+
+    # #   - name: Test debug build on linux
+    # #     shell: bash -e -l {0}
+    # #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    # #     run: ctest --output-on-failure
+    # #     working-directory: builddir
+
+    # #   - name: Test Moved Installation
+    # #     if: contains(matrix.os, 'ubuntu') && contains(matrix.llvm-version, '11')
+    # #     shell: bash -e -l {0}
+    # #     run: |
+    # #       mv inst inst.moved
+    # #       cp src/examples/expr2.f90 expr2.F90
+    # #       rm -rf src
+    # #       inst.moved/bin/lfortran expr2.F90 -o expr2
+    # #       ./expr2
+    # #       inst.moved/bin/lfortran --backend=c expr2.F90 -o expr2b
+    # #       ./expr2b
+    # #       inst.moved/bin/lfortran --openmp --backend=cpp expr2.F90 -o expr2c
+    # #       ./expr2c
       # end of Debug build on linux
 
       # below code is from "Check Third Party Code Compilation"
